### ISSUE TITLE
Contributions from Workshop Participants

### ISSUE THREAD

**Issue by chrisdburr** [chrisdburr/turing-commons#10]
### Add yourself as a contuributor

To add yourself as a contributor for this project is really easy, thanks to an installed bot that automates the process for us. 

Simply type the following text as a new comment, replacing the text 'yourusername' with your GitHub username:

@all-contributors please add @yourusername for tutorial

**Comment by tedarbyshire** [comment]
@all-contributors please add @tedarbyshire for tutorial

**Comment by dingaaling** [comment]
@all-contributors please add @dingaaling for tutorial

**Comment by AusteSimkute** [comment]
@all-contributors please add @AusteSimkute for tutorial

**Comment by mayaracarneiro2** [comment]
@all-contributors please add @mayaracarneiro2 for tutorial

**Comment by GregorMilliganUoN** [comment]
@all-contributors please add @GregorMilliganUoN for tutorial

**Comment by ejmoss** [comment]
@all-contributors please add @ejmoss for tutorial

**Comment by aragn** [comment]
@all-contributors please add @aragn for tutorial

**Comment by fatemehnj** [comment]
@all-contributors please add @fatemehnj for tutorial

**Comment by emmavestesson** [comment]
@all-contributors please add @emmavestesson for tutorial

**Comment by anandkumaresh** [comment]
@all-contributors please add @anandkumaresh for tutorial

**Comment by AshmitaRandhawa** [comment]
@all-contributors please add @AshmitaRandhawa for tutorial

**Comment by AshmitaRandhawa** [comment]
@all-contributors please add @AshmitaRandhawa for tutorial

**Comment by chrisdburr** [comment]
@all-contributors please add @AshmitaRandhawa for tutorial
